config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  # root 'public_recipes#index'
  root 'foods#index'
  resources :recipes, only: [:index, :new, :show, :create, :update, :destroy] do
    resources :recipe_foods, only: [:new, :create, :edit, :update, :destroy]
  end
  resources :foods, only: [:index, :new, :create, :destroy]
  resources :public_recipes, only: [:index]
  resources :shopping_list, only: [:index]
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)

    can :manage, Recipe, user_id: user.id
    can :manage, Food, user_id: user.id
    can :read, :all

    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user

  validates :name, presence: true
  validates :measurement_unit, presence: true
  validates :price, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  has_many :recipe_foods, dependent: :destroy
  has_many :recipes, through: :recipe_foods
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user

  validates :name, presence: true
  validates :preparation_time, presence: true
  validates :cooking_time, presence: true
  validates :description, presence: true

  has_many :recipe_foods
  has_many :foods, through: :recipe_foods
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :recipes
  has_many :foods
  has_many :recipe_foods, through: :recipes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:name, :email, :password, :password_confirmation)
    end
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :password_confirmation, :current_password)
    end
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    @user = current_user
    @foods = Food.includes(:user).where(user: @current_user)
  end

  def show
    @food = Food.find(params[:id])
  end

  def new
    @food = Food.new
  end

  def create
    @food = Food.new(food_params)
    if @food.save
      redirect_to foods_path, notice: "food #{@food.name} was successfully created!"
    else
      # render :new, notice: 'food could not be created!'
      redirect_to new_food_path, notice: 'food could not be created!'
    end
  end

  def destroy
    @food = Food.find(params[:id])
    @food.destroy
    redirect_to foods_path, notice: "food #{@food.name} deleted successfully!"
  end

  private

  def food_params
    params.require(:food).permit(:name, :user_id, :measurement_unit, :price)
  end
end

app/controllers/public_recipes_controller.rb
class PublicRecipesController < ApplicationController
  def index
    @recipes = Recipe.all.where(public: true).order(created_at: :desc).includes(:user)
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  def new
    @recipe_food = RecipeFood.new
    @recipe = Recipe.find(params[:recipe_id])
    @foods = Food.all
  end

  def create
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = RecipeFood.new(recipe_food_params)
    @recipe_food.recipe_id = @recipe.id

    if @recipe_food.save
      redirect_to recipe_path(params[:recipe_id]), notice: 'recipe_food was successfully created!'
    else
      redirect_to recipe_path(params[:recipe_id]), notice: 'recipe_food could not be created!'
    end
  end

  def edit
    @recipe_food = RecipeFood.find(params[:id])
    @foods = Food.all
  end

  def update
    recipe_food = RecipeFood.find(params[:id])

    if recipe_food.update(recipe_food_params)
      redirect_to recipe_path(params[:recipe_id]), notice: 'Ingredient was edited successfully!'
    else
      redirect_to recipe_path(params[:recipe_id]), notice: 'Error editing ingredient!'
    end
  end

  def destroy
    @recipe_food = RecipeFood.includes(:food).find(params[:id])
    @recipe_food.destroy
    redirect_to recipe_path(params[:recipe_id]), notice: 'recipe_food  deleted successfully!'
  end

  private

  def recipe_food_params
    params.require(:recipe_food).permit(:food_id, :recipe_id, :quantity)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = current_user.recipes
  end

  def show
    @recipe = Recipe.find(params[:id])
    @ingridients = RecipeFood.where(recipe_id: params[:id]).includes(:food)
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    if @recipe.save
      redirect_to recipes_path, notice: "recipe #{@recipe.name} was successfully created!"
    else
      # render :new, notice: 'recipe could not be created!'
      redirect_to new_recipe_path, notice: 'recipe could not be created!'
    end
  end

  def update
    recipe = Recipe.find(params[:id])
    recipe.update(public: !recipe.public)

    redirect_to recipe_path(recipe.id), notice: "The recipe is now #{recipe.public ? 'public' : 'private'}!"
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    redirect_to recipes_path, notice: "recipe #{@recipe.name} deleted successfully!"
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :user_id, :description, :cooking_time, :preparation_time, :public)
  end
end

app/controllers/shopping_list_controller.rb
class ShoppingListController < ApplicationController
  def index
    @recipe_foods = current_user.recipe_foods.includes(:food)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/foods/index.html.erb
<div>
  <h1>Listing foods</h1>
<div class="text-center m-1">
<div class="food-btn m-1">
    <%= link_to "Add new food", new_food_path, class: "btn btn-primary" %>
<div>
<br/>

</div>
  <table class = "table table-hover">
  <thead>
    <tr>
      <th scope="col">Food</th>
      <th scope="col">Measurement Unit</th>
      <th scope="col">Unit Price</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @foods.each do |food| %>     
      <tr>
        <td><%= food.name %></td>
        <td><%= food.measurement_unit %></td>
        <td><%= food.price %></td>
        <td>
          <%= button_to "Delete", food, method: :delete, class: "btn btn-danger" %>
        </td>
      </tr>
    <% end %>
  </tbody>
  </table>

</div>

app/views/foods/new.html.erb
<h2>Create a food to the current user</h2>

<%= form_with model: @food do |f| %>
  <%= f.hidden_field :user_id, value: current_user.id%>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :measurement_unit %>
    <%= f.text_field :measurement_unit, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :price %>
    <%= f.text_field :price, class: "form-control" %>
  </div>
  <%= f.submit "Create Food", class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <div class = "container">
    <br/>
    <% if notice %>
      <%= render 'shared/alerts' %>
    <% end %>
    <% if alert %>
      <%= render 'shared/popup' %>
    <% end %>
      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
  </body>
  </body>
</html>

app/views/public_recipes/index.html.erb
<div class="container">
    <h1 class="text-center m-4 py-4 text-5xl">Public Recipes</h1>
    <ul class="flex flex-col gap-4">
      <% @recipes.each do |recipe| %>
        <li class="card p-3 m-4">
          <%= link_to recipe_path(recipe.id), class: "link" do  %>
            <div class="recipe-container justify-content-around link">
              <div class = ""> 
                <h3 class=""><%= recipe.name %></h3>
                <h3>by <span class=""><%= recipe.user.name %></span></h3>
              </div>

              <div class="">
                <h3>Total food items: <span class=""><%= recipe.foods.count %></span></h3>
                <h3>Total price: <span class=""> $<%= recipe.recipe_foods.includes(:food).map {|r| r.food.price.to_i * r.quantity.to_i }.sum %></span></h3>

              </div>
            </div>
          <% end %>
        </li>
      <% end %>
    </ul>
</div>

app/views/recipe_foods/edit.html.erb
<div class="card">
<div class="card-header">
  <h3>Edit ingredient</h3>
</div>
  <div class="card-body">
    <%= form_with model: @recipe_food, url: recipe_recipe_food_path, method: :put do |f| %>
      <%= f.hidden_field :id, value: @recipe_food.id %>
      <%= f.hidden_field :recipe_id, value: @recipe_food.recipe_id %>
      <div class="field form-group m-3">
        <%= f.select :food_id, @foods.map { |food| [food.name, food.id] }, {}, { class: "form-control p-2"} %>
      </div>
      <div class="field form-group m-3">
        <%= f.number_field :quantity, placeholder: 'Quantity', min: 0, required: true, class: "form-control p-2" %>
      </div>
      <div class="actions">
        <%= f.submit "Add ingredient", class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/recipe_foods/new.html.erb
<div class="card">
  <div class="card-header">
  <h3>Add ingredient for <%= @recipe.name %></h3>
  </div>
  <div class="card-body">
  <% if @foods.present? %>
    <%= form_with model: @recipe_food, url: recipe_recipe_foods_path do |f| %>
      <div class="field form-group m-3">
        <%= f.select :food_id, @foods.map { |food| [food.name, food.id] }, {}, { class: "form-control p-2"} %>
      </div>
      <div class="field form-group m-3">
        <%= f.number_field :quantity, placeholder: 'Quantity', min: 0, required: true, class: "form-control p-2" %>
      </div>
      <div class="actions">
        <%= f.submit "Add ingredient", class: 'btn btn-primary' %>
      </div>
    <% end %>
  <% else %>
    <h3 class="font-bold mb-10">No food available for <%= current_user.name %> head over to <%= link_to "foods page", foods_path %> to add new food</h3>
<% end %>
  </div>
</div>

app/views/recipes/index.html.erb
<div>
  <% if @recipes.length !=0 %>
    <h1 class="">My recepies</h1>
    <div class="food-btn m-4">
      <%= link_to "Add new recipe", new_recipe_path, class: "btn btn-primary" %>
    </div>

    <% @recipes.each do |recipe| %>
      <div class="card m-4">
        <div class="recipe-container justify-content-around">
          <div class="recipe-name">
            <%= link_to recipe_path(recipe.id), class: "nav-link m-4" do %>
              <h3>
                <%= recipe.name %>
              </h3>
            <% end %>
              <%= button_to "Remove", recipe_path(recipe.id), method: :delete, class: 'btn btn-danger m-4' if can? :destroy, recipe %>
          </div>

          <div class="">
            <p class="m-4"><%= truncate recipe.description, length: 240 %></p>
          </div>
        </div>
      </div>
    <% end %>
    <% else %>
      <h1 class="text-center m-4">There are no recipes</h1>
      <div class="text-center m-4">
        <%= link_to "Add new recipe", new_recipe_path, class: "btn btn-primary" %>
      </div>
    <% end %>

</div>

app/views/recipes/new.html.erb
<div class="card">
  <div class="card-header">
    <h4> Create a new recipe </h4>
  </div>
  <div class="card-body">
  <%= form_with model: @recipe do |f| %>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <div class="field  form-group">    
      <%= f.text_field :name, placeholder: 'Recipe name', class: "form-control" %>
    </div>
    <br/>
    <div class="field  form-group">
      <%= f.number_field :preparation_time, placeholder: 'Preparation Time (minutes)', class: "form-control" %>
    </div>
    <br/>
    <div class="field  form-group">
      <%= f.number_field :cooking_time, placeholder: 'Cooking Time (minutes)', class: "form-control" %>
    </div>
    <br/>
    <div class="field  form-group">
    <%= f.text_area :description, placeholder: 'Description', size: '50x5', class: "form-control" %>
    </div>
    <br/>

    <div>
      <%= f.label :public, "Public" %>
      <%= f.check_box :public %>
    </div>
    <br/>
    <%= f.submit "Create recipe", class: 'btn btn-primary'%>
  <% end %>
  </div>
</div>

app/views/recipes/show.html.erb
<div class="container mx-auto m-3">
  <div class="p-3 card m-2">
    <h5 class="text-center"><%= @recipe.name %></h5>
    <div class="d-flex flex-row p-2 justify-content-between">
      <div class="d-flex flex-column">
        <h5 class="m-3">
          Preparation time: <%= (@recipe.preparation_time)/60 %> hr <%= (@recipe.preparation_time)%60 > 0 ? "#{(@recipe.preparation_time)%60} min": " " %>
        </h5>
        <h5 class="m-3 font-bold">
          Cooking time: <%= (@recipe.cooking_time)/60 %> hr <%= (@recipe.cooking_time)%60 > 0 ? "#{(@recipe.cooking_time)%60} min": " " %>
        </h5>
      </div>

      <div class="d-flex flex-column m-2">
        <% if can? :manage, @recipe %>
          <%= button_to "Make it #{@recipe.public ? 'private' : 'public'}", recipe_path(@recipe.id), class: @recipe.public ? 'btn btn-warning' : 'btn btn-success', method: :patch %>
        <% end %>

          <label class="switch mt-4">
            <input type="checkbox",recipe_path(@recipe.id), method: :patch>
            <span class="slider round"></span>
          </label>

      </div>

    </div>

    <div class="d-flex flex-column justify-content-start">
      <p class="p-2 ms-3">
        Descrition: <%= @recipe.description %>
      </p>
    </div>

    <div class="d-flex flex-row mt-2 justify-content-between p-3">
      <div class="">
        <% if can? :manage, @recipe %>
          <button class="btn btn-info">
            <%= link_to "Generate shoping list", shopping_list_index_path, class: "link"%>
          </button>
        <% end %>
      </div>
      <div class="">
        <% if can? :manage, @recipe %>
          <%= link_to "Add ingredient", new_recipe_recipe_food_path(@recipe.id), class: "btn btn-secondary" %>
        <% end %>
      </div>
    </div>
    <hr class="my-8">
    <div>
      <% if @ingridients.present? %>
        <table class="table">
          <thead class="bg-gray-800">
            <tr class="h-10">
              <th class="p-1">Food</th>
              <th class="p-1">Quanity</th>
              <th class="p-1">Price</th>
              <th class="p-1">Value</th>
              <th class="p-1">Action</th>
              <th class="p-1"></th>
            </tr>
          </thead>
          <tbody class="">
            <% @ingridients.each do |ingredient| %>
              <tr class="h-10">
                <td class="p-1"><%= ingredient.food.name %></td>
                <td class="p-1"><%= ingredient.quantity %> <%= ingredient.food.measurement_unit %></td>
                <td class="p-1">$<%= ingredient.food.price %></td>
                <td class="p-1">$<%= ingredient.food.price * ingredient.quantity || 0 %></td>
                <td class="p-1">
                  <%= link_to "Modify", edit_recipe_recipe_food_path(recipe_id: @recipe.id, id: ingredient.id), class: 'btn btn-success' if can? :manage, @recipe %>
                </td>
                <td class="p-1">
                  <%= button_to "Delete", recipe_recipe_food_path(recipe_id: @recipe.id, id: ingredient.id), method: :delete, class: 'btn btn-danger' if can? :manage, @recipe%>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
  </button>
</div>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
<div class="container-fluid">
  <% if current_user %>
  <p class="navbar-brand">Welcome <%= (current_user.name).upcase %></p>
  <% end %>
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
  </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Sign Out", destroy_user_session_path,  data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Foods",  foods_path, class: "nav-link" %>
          </li>
          </li>
            <%= link_to "Recipes",  recipes_path, class: "nav-link" %>
          </li>
          </li>
            <%= link_to "Public Recipes", public_recipes_path, class: "nav-link" %>
          </li>
          </li>
          <%= link_to "Shopping list", shopping_list_index_path, class: "nav-link" %>
        </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign IN", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_popup.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= alert %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
  </button>
</div>

app/views/shopping_list/index.html.erb
<h1 class="font-bold text-4xl mb-10 text-center">Shopping List for <%= current_user.name %></h1>
<div class="mb-10 text-center">
  <span class="text-2xl">
    Amount of food items to buy: <span class="font-bold"><%= @recipe_foods.length %></span>
  </span>
  <span class="text-2xl">
    Total value of food needed: <span class="font-bold">$<%= @recipe_foods.map {|r| r.food.price.to_i * r.quantity.to_i }.sum %></span>
  </span>
</div>
<table class="table">
  <thead class="">
    <tr>
      <th class="p-4">Food</th>
      <th class="p-4">Quantity</th>
      <th class="p-4">Price</th>
      <th class="p-4">Amount</th>
    </tr>
  </thead>
  <tbody class="bg-gray-300 p-20">
    <% @recipe_foods.each do |r|%>
      <tr class="h-16">
        <td class="p-4"><%= r.food.name %></td>
        <td class="p-4"><%= r.quantity %> <%= r.food.measurement_unit %></td>
        <td class="p-4">$<%= r.food.price %></td>
        <td class="p-4">$<%= r.food.price.to_i * r.quantity.to_i %></td>
      </tr>
    <% end %>
  </tbody>
</table>